language: java
jdk: oraclejdk8
env:
  global:
    - T_DIR="`pwd`/travis"

before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | gpg --import
- echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust

install: true

script: 
  mvn --settings travis/settings.xml clean install -DskipITs=false -DskipTests=false -Dgpg.skip -Dmaven.javadoc.skip=true  -B -V

deploy:
  -
    provider: script
    script: "mvn versions:set -DnewVersion=${TRAVIS_TAG} && mvn clean deploy -DskipTests=true -B -U -P release --settings travis/settings.xml"
    skip_cleanup: true
    on:
      repo: RogerParkinson/madura-bundles
      tags: true
      jdk: oraclejdk8